### ISSUE TITLE
how to hook up spade decoder to other encoder

### ISSUE THREAD

**Issue by kkkris7** [clovaai/spade#12]
Thank you for the amazing work for the first! I am thinking to apply the spade decoder to hook up with other encoder(like Bert, LayoutLM) that can be pretrained. Wondering what is the best procedure to do it. Any instructions will be very helpful! Thanks!

**Comment by whwang299** [comment]
Hi @kkkris7 

Thanks for having interest in our work. 

You can start from this part.
https://github.com/clovaai/spade/blob/a85574ceaa00f1878a23754f283aa66bc2daf082/spade/model/model.py#L54-L58

But due to the use of "2d relative attention", you may need to tweak other models as we have done on "bert". See below.
https://github.com/clovaai/spade/blob/a85574ceaa00f1878a23754f283aa66bc2daf082/spade/model/model_spade_encoder.py#L39

By the way if you simply want to see the performance of BERT, you may change
https://github.com/clovaai/spade/blob/a85574ceaa00f1878a23754f283aa66bc2daf082/configs/cord.1.5layers.train.yaml#L17-L22
to 
```
input_embedding_comments:
  - absPos
```
and 
https://github.com/clovaai/spade/blob/a85574ceaa00f1878a23754f283aa66bc2daf082/configs/cord.1.5layers.train.yaml#L98
to
```
  no_rel_attention: true
```

Also, if you want to focus on pretraining algorithm, the code base of [BROS](https://arxiv.org/abs/2108.04539) will be released soon (I guess around AAAI22). 

Good luck!

Wonseok

**Comment by kkkris7** [comment]
Hi @whwang299,
Thank you for your response! I checked the BROS paper and it's super awesome! 

I find you and your team mentioned using LayoutLM encoder + Spade decoder in the paper. And that's exactly the path that I am trying to explore. As you suggested in this thread if I understand it correctly did you tweak the LayoutLM model here https://github.com/clovaai/spade/blob/a85574ceaa00f1878a23754f283aa66bc2daf082/spade/model/model_spade_encoder.py#L39 as well?  And do I need to do something else to make sure the encode and decoder can be hooked up?

Thank you!

**Comment by whwang299** [comment]
As far as I remember, no, you don't need to touch other parts except the L39 above and the encoder input arguments (see below).
https://github.com/clovaai/spade/blob/a85574ceaa00f1878a23754f283aa66bc2daf082/spade/model/model.py#L160-L170.
To minimize the change, you may prepare something like `TwoDimLayoutLMEncoder` and can ignore unnecessary inputs like `rn_center_x_toks` which includes the relative x position between tokens.

By the way, `BROS` and `spade` does not share the codebase much. So, depending on your purpose, it could be better choice to start from `BROS` source code (you may contact the first author Taekgyu to know the release date).

Best,
Wonseok

**Comment by kkkris7** [comment]
Thank you so much for the detailed instruction!
